# Generated by Django 3.0 on 2019-12-12 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deskripsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('harga', models.IntegerField(default=0)),
                ('foto', models.CharField(max_length=200)),
                ('deskripsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Deskripsi')),
            ],
        ),
    ]
